title: Tomasz Berbeka # your name (or website title) here
logo: "/images/tom_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Description number one 
  <br><br>
  Description number two 
  <br><br>
  <a href="https://www.linkedin.com/in/tomasz-berbeka/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
